In [26]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
!ls tmp/data

README.txt            sample_submission.csv train.csv
data_explanation.xlsx test.csv

In [4]:
df =pd.read_csv('tmp/data/train.csv')
df

,id,source,text,label
0,80074aa43,news4vip,まともに相手されてない人との関係なんて\nそんな大事にするものか？,0
1,6378fea6b,livejupiter,最近はアヘアヘQSマンやない？ ｲｲ!(・∀・)+1-0(・Ａ・)ｲｸﾅｲ!,0
2,c535f5613,livejupiter,日本人として生まれても無能な低学歴って分かったら日本人の権利剥奪して追放すべきやろ\n甘えるな,1
3,e76638295,livejupiter,よくよく思えば川上は配布にしたらとんでもなく有能だよな\nガチャから引いたら圧倒的歓喜レベルやで,0
4,51e4036bf,newsplus,押井は原作レイプの専門家だから\n原作マンガの真意を誤解させることに関してはプロだが\nそれ...,0
...,...,...,...,...
5251,42b5f86b0,news4vip,車じゃなくてもよくない？\nケーブル網を張り巡らせてリフトみたいなのを付けるとか,0
5252,402ce15d9,livejupiter,左やぞ？\n出すなら下水流,0
5253,0739a9fcb,newsplus,日本によって、けんけんガクガクの議論を持たらされた韓国は被害者\n\n日本人がしっかり考えな...,0
5254,d496c7dc8,news4vip,ゴムボート買って、沖まで漕いで行ったら？\n魚の血を塗っておけばサメが食べてくれるよ,0
5255,d1838f4f0,news4vip,男は美化してないだろ？普通にエロい部分や格好悪い所も描かれてる\n女の方は主人公美少女しかい...,0

In [5]:
df['label'].value_counts()

label
0    4950
1     306
Name: count, dtype: int64

In [24]:
df_train, df_test = train_test_split(df, test_size=600, stratify=df['label'], random_state=123)

df.shape, df_train.shape, df_test.shape, df_test.shape[0]/ df_train.shape[0]

((5256, 4), (4656, 4), (600, 4), 0.12886597938144329)

In [22]:
df_train['label'].value_counts()

label
0    4385
1     271
Name: count, dtype: int64

In [23]:
df_test['label'].value_counts()

label
0    565
1     35
Name: count, dtype: int64

,id,source,text,label
2500,b1b0d5e6c,newsplus,手引きしたのは高い確率で大院君だよなぁ,0
605,a5e29c5f1,livejupiter,いや別にワイが困るわけじゃないからええけど対応大変やなぁと思ってな,0
1172,bd72cb57e,newsplus,そこで家族会すら総スカンを食らった極左を出すあたり頭が逝ってるな\n結局動かぬ証拠だから動か...,0
3837,66387bae8,news4vip,もともとB'zが好きだったんだが松本のソロアルバムでtake5カバーしててな\nそれで原曲聴...,0
4151,b80dc3a94,livejupiter,スタンドって本体の内面現すんだよな\n\nいろいろ想像するとおもろいわ\n何でDIOは時止め...,0
...,...,...,...,...
1554,18be9598d,newsplus,すまん。\nありがとう。,0
3500,e2c03cc22,livejupiter,人集まったり伸びたらそうするで\nあっちで１からやっても誰もおらんからな\nここでもおらんか...,0
1401,98465a0b2,newsplus,（；ﾟДﾟ）スマホだったら、おーぷんstormってのがありますね\n今スマホにインスコして書...,0
361,c4ee8a9f0,news4vip,実際には戦わなきゃ強姦されて略奪されて殺されるだけ\n日本もベトナムもイラクも米軍兵に蹂躙さ...,0
317,7b28c4717,livejupiter,女が近くにいるとムラムラして勉強出来ない\n家にいるとシコってしまって勉強出来ない\nどうすれば,0

In [40]:
np.random.seed(seed=12345)
hold = np.random.choice([0,1,2,3,4], size=df_train.shape[0])
df_train['hold'] = hold

print(df_train['hold'].value_counts(normalize=True))

pd.crosstab(df_train['hold'], df_train['label'])#, normalize='index')

hold
1    0.207689
3    0.204253
4    0.198239
2    0.197165
0    0.192655
Name: proportion, dtype: float64

label    0   1
hold
0      847  50
1      907  60
2      869  49
3      901  50
4      861  62

In [41]:
df_train

,id,source,text,label,hold
2500,b1b0d5e6c,newsplus,手引きしたのは高い確率で大院君だよなぁ,0,2
605,a5e29c5f1,livejupiter,いや別にワイが困るわけじゃないからええけど対応大変やなぁと思ってな,0,1
1172,bd72cb57e,newsplus,そこで家族会すら総スカンを食らった極左を出すあたり頭が逝ってるな\n結局動かぬ証拠だから動か...,0,4
3837,66387bae8,news4vip,もともとB'zが好きだったんだが松本のソロアルバムでtake5カバーしててな\nそれで原曲聴...,0,1
4151,b80dc3a94,livejupiter,スタンドって本体の内面現すんだよな\n\nいろいろ想像するとおもろいわ\n何でDIOは時止め...,0,2
...,...,...,...,...,...
1554,18be9598d,newsplus,すまん。\nありがとう。,0,3
3500,e2c03cc22,livejupiter,人集まったり伸びたらそうするで\nあっちで１からやっても誰もおらんからな\nここでもおらんか...,0,3
1401,98465a0b2,newsplus,（；ﾟДﾟ）スマホだったら、おーぷんstormってのがありますね\n今スマホにインスコして書...,0,3
361,c4ee8a9f0,news4vip,実際には戦わなきゃ強姦されて略奪されて殺されるだけ\n日本もベトナムもイラクも米軍兵に蹂躙さ...,0,2
317,7b28c4717,livejupiter,女が近くにいるとムラムラして勉強出来ない\n家にいるとシコってしまって勉強出来ない\nどうすれば,0,0

In [42]:
df_train.to_csv('tmp/hatespeech_train.csv', index=False)
df_test.to_csv('tmp/hatespeech_test.csv', index=False)