In [43]:
import pandas as pd
import numpy as np

In [7]:
!ls tmp/HT/cable_classify_15classes_HT

images    test.csv  train.csv

In [11]:
df_train=pd.read_csv('tmp/HT/cable_classify_15classes_HT/train.csv')
df_train

                  image          label
0     b8dc2c14_trim.jpg           HDMI
1     0f785409_trim.jpg     USB_Type_C
2     cf3ff1a0_trim.jpg       USB_Mini
3     2f111928_trim.jpg           Dock
4     a4c6af0c_trim.jpg    USB_Micro_B
...                 ...            ...
1395  f46733e1_trim.jpg      Lightning
1396  0def2c97_trim.jpg  USB_Micro_B_W
1397  1706be6c_trim.jpg     USB_Type_C
1398  d29d5370_trim.jpg    Lightning_T
1399  c75d3f1f_trim.jpg     USB_Type_C

[1400 rows x 2 columns]

In [17]:
df_train['label'].value_counts().sort_values(ascending=False)

USB_Micro_B         278
Lightning           252
USB_Type_C          218
USB_Type_A          117
HDMI                 92
Lightning_T          77
VGA                  76
DisplayPort          76
Mini_DisplayPort     75
USB_Mini             63
USB_Micro_B_W        44
Dock                 12
USB_Type_B            8
RJ_45                 7
USB_Micro_B_3.1       5
Name: label, dtype: int64

In [22]:
df_train['label'].value_counts().sort_values(ascending=False).index

Index(['USB_Micro_B', 'Lightning', 'USB_Type_C', 'USB_Type_A', 'HDMI',
       'Lightning_T', 'VGA', 'DisplayPort', 'Mini_DisplayPort', 'USB_Mini',
       'USB_Micro_B_W', 'Dock', 'USB_Type_B', 'RJ_45', 'USB_Micro_B_3.1'],
      dtype='object')

In [24]:
val = df_train['label'].value_counts().sort_values(ascending=False).index

mapping = {val[i]:i for i in range(len(val))}
mapping

{'USB_Micro_B': 0,
 'Lightning': 1,
 'USB_Type_C': 2,
 'USB_Type_A': 3,
 'HDMI': 4,
 'Lightning_T': 5,
 'VGA': 6,
 'DisplayPort': 7,
 'Mini_DisplayPort': 8,
 'USB_Mini': 9,
 'USB_Micro_B_W': 10,
 'Dock': 11,
 'USB_Type_B': 12,
 'RJ_45': 13,
 'USB_Micro_B_3.1': 14}

In [30]:
df_train['label_idx'] = df_train['label'].map(mapping)
df_train.head()

               image        label  label_idx
0  b8dc2c14_trim.jpg         HDMI          4
1  0f785409_trim.jpg   USB_Type_C          2
2  cf3ff1a0_trim.jpg     USB_Mini          9
3  2f111928_trim.jpg         Dock         11
4  a4c6af0c_trim.jpg  USB_Micro_B          0

In [51]:
list_0_6 = [i for i in range(7)]
np.random.seed(seed=123)
df_train['fold'] = np.random.choice(list_0_6, size=df_train.shape[0])
df_train.head()

               image        label  label_idx  fold
0  b8dc2c14_trim.jpg         HDMI          4     6
1  0f785409_trim.jpg   USB_Type_C          2     5
2  cf3ff1a0_trim.jpg     USB_Mini          9     6
3  2f111928_trim.jpg         Dock         11     2
4  a4c6af0c_trim.jpg  USB_Micro_B          0     4

In [54]:
df_train = df_train.rename(columns={'label':'label_original', 'label_idx':'label'})
df_train

                  image label_original  label  fold
0     b8dc2c14_trim.jpg           HDMI      4     6
1     0f785409_trim.jpg     USB_Type_C      2     5
2     cf3ff1a0_trim.jpg       USB_Mini      9     6
3     2f111928_trim.jpg           Dock     11     2
4     a4c6af0c_trim.jpg    USB_Micro_B      0     4
...                 ...            ...    ...   ...
1395  f46733e1_trim.jpg      Lightning      1     2
1396  0def2c97_trim.jpg  USB_Micro_B_W     10     3
1397  1706be6c_trim.jpg     USB_Type_C      2     0
1398  d29d5370_trim.jpg    Lightning_T      5     1
1399  c75d3f1f_trim.jpg     USB_Type_C      2     6

[1400 rows x 4 columns]

In [55]:
df_test=pd.read_csv('tmp/HT/cable_classify_15classes_HT/test.csv')
df_test

                 image             label
0    21900f41_trim.jpg         Lightning
1    1c49f22f_trim.jpg        USB_Type_C
2    09895de0_trim.jpg       USB_Micro_B
3    a89d6642_trim.jpg              HDMI
4    b1ac3a14_trim.jpg          USB_Mini
..                 ...               ...
243  23cd823b_trim.jpg       USB_Micro_B
244  5a39cadd_trim.jpg         Lightning
245  0985b889_trim.jpg  Mini_DisplayPort
246  023849c3_trim.jpg        USB_Type_A
247  24fae883_trim.jpg               VGA

[248 rows x 2 columns]

In [56]:
df_test['label_idx'] = df_test['label'].map(mapping)
df_test = df_test.rename(columns={'label':'label_original', 'label_idx':'label'})
df_test

                 image    label_original  label
0    21900f41_trim.jpg         Lightning      1
1    1c49f22f_trim.jpg        USB_Type_C      2
2    09895de0_trim.jpg       USB_Micro_B      0
3    a89d6642_trim.jpg              HDMI      4
4    b1ac3a14_trim.jpg          USB_Mini      9
..                 ...               ...    ...
243  23cd823b_trim.jpg       USB_Micro_B      0
244  5a39cadd_trim.jpg         Lightning      1
245  0985b889_trim.jpg  Mini_DisplayPort      8
246  023849c3_trim.jpg        USB_Type_A      3
247  24fae883_trim.jpg               VGA      6

[248 rows x 3 columns]

In [60]:
!ls tmp/PT/cable_classify_15classes_PT

images

In [61]:
df_train.to_csv('tmp/PT/cable_classify_15classes_PT/train.csv', index=False)
df_test.to_csv('tmp/PT/cable_classify_15classes_PT/test.csv', index=False)